### ISSUE TITLE
Add support for pastes in "High Contrast Mode" 

### ISSUE THREAD

**Issue by andrerfcsantos** [andrerfcsantos/wordle-discord-bot#1]
## Description

Wordle allows users to play in "High Contrast Mode". In this mode, the green squares (🟩) of a letter in the right position are replaced by an orange square (🟧), and the yellow squares indicating a letter in the wrong position (🟨) are replaced by a blue square (🟦).

This is an example of a paste using "High Contrast Mode":

```
Wordle 393 6/6*

⬛⬛🟦⬛⬛
⬛🟧⬛⬛🟧
⬛🟧⬛⬛🟧
⬛🟧⬛⬛🟧
⬛🟧⬛⬛🟧
🟧🟧🟧🟧🟧
```

## Tasks

- [ ] Make the regex parsing the pastes support orange squares (🟧) and blue squares (🟦) (see file [wordle.go](https://github.com/andrerfcsantos/wordle-discord-bot/blob/main/wordle/wordle.go))
- [ ] Add some tests covering pastes in High Contrast Mode!
- [ ] (Optional) Replace orange squares (🟧) by green squares (🟩) and blue squares(🟦) by yellow squares (🟨) before saving the attempt to the database.

## Contributing to this issue

If you are interested in contributing to this issue, post a message below showing your interest. This avoids having more than one person working on an issue making duplicate work. Nevertheless, you are free to collaborate with others on an issue!
