### ISSUE TITLE
Add the `/wordle untrack` command

### ISSUE THREAD

**Issue by andrerfcsantos** [andrerfcsantos/wordle-discord-bot#4]
## Description

Currently, the `/wordle track` command allows a user to make the bot listen for wordle copy/paste messages in that channel.
The reverse command `/wordle untrack` should also be possible. "Untracking" a channel should:

- Remove the channel from the list of tracked channels.
- Delete (or mark as deleted) from the database messages from that channel.
- Remove the ✅ reactions the bot might have posted in the channel.

## Tasks

- [ ] Add a new [Application Command](https://discord.com/developers/docs/interactions/application-commands) in [application_commands.go](https://github.com/andrerfcsantos/wordle-discord-bot/blob/main/wordlebot/application_commands.go)
- [ ] Add a new handler for the newly added Application Command in [interactions.go](https://github.com/andrerfcsantos/wordle-discord-bot/blob/main/wordlebot/interactions.go) that performs the actions listed above
- [ ] Update the README with the new command
- [ ] (Optional) If going with the "marking as deleted" route instead of actually deleting the attempts from the database, a new migration adding a column "deleted" to the `attempts` table should be made and the code should start to use that field in queries. This task is optional, as it makes the difficulty of the task greatly increase. The simpler solution of just deleting records from the database when untracking a channel is fine for now.

## Contributing to this issue

If you are interested in contributing to this issue, post a message below showing your interest. This avoids having more than one person working on an issue making duplicate work. Nevertheless, you are free to collaborate with others on an issue!
