### ISSUE TITLE
Add the `/wordle stats` command

### ISSUE THREAD

**Issue by andrerfcsantos** [andrerfcsantos/wordle-discord-bot#5]
## Description

Right now a user has no access to their personal stats other than the ones shown in leaderboard.
We should have a `/wordle stats` command that prints some stats for the current user.
Some stats can include:

- Number of games played
- Total score
- Average guesses
- Number of successes/failures
- Win %

To make the output look good, we can use discord [embed messages](https://autocode.com/tools/discord/embed-builder/) that discordgo also supports via the [discordgo.MessageEmbed](https://pkg.go.dev/github.com/bwmarrin/discordgo#MessageEmbed) type.

## Tasks

- [ ] Add a new [Application Command](https://discord.com/developers/docs/interactions/application-commands) in [application_commands.go](https://github.com/andrerfcsantos/wordle-discord-bot/blob/main/wordlebot/application_commands.go)
- [ ] Add a new handler for the newly added Application Command in [interactions.go](https://github.com/andrerfcsantos/wordle-discord-bot/blob/main/wordlebot/interactions.go) that prints some wordle stats of the user
- [ ] Update the README with the new command

## Contributing to this issue

If you are interested in contributing to this issue, post a message below showing your interest. This avoids having more than one person working on an issue making duplicate work. Nevertheless, you are free to collaborate with others on an issue!
